Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
score=[20,19,56]
type(score)
<class 'list'>
print("the value of x is:",x)
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    print("the value of x is:",x)
NameError: name 'x' is not defined
x=10
y=2
score=45
print("the value of x is:",x)
the value of x is: 10
print("marks obtained is",score)
marks obtained is 45
print("x is:",x,"y is:",y)
x is: 10 y is: 2
print("x is:",x\n "y is:",y)
SyntaxError: unexpected character after line continuation character
print("x is:",x\n"y is:",y)
SyntaxError: unexpected character after line continuation character
print("x is:",x \n "y is:",y)
SyntaxError: unexpected character after line continuation character
